name: Build and Push Docker Image to ECR

on:
    push:
      branches:
        - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step to build the Docker image locally
    - name: Build Docker image locally
      run: |
          docker build -t my-local-image:latest .

    # Step to tag the local image with ECR registry and push it to Amazon ECR
    - name: Tag and Push Docker image to Amazon ECR
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sample-repo
          IMAGE_TAG: latest
      run: |
          # Tag the local image with the ECR registry
          docker tag my-local-image:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          # Push the tagged image to ECR
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
